### ISSUE TITLE
Remove eventual crate

### ISSUE THREAD

**Issue by agourlay** [qdrant/wal#23]
https://github.com/carllerche/eventual

This crate is deprecated in favor of [futures](https://crates.io/crates/futures).

It pulls a problematic version of `time`

```
Crate:         time
Version:       0.1.43
Title:         Potential segfault in the time crate
Date:          2020-11-18
ID:            RUSTSEC-2020-0071
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:      Upgrade to >=0.2.23
Dependency tree: 
time 0.1.43
```

**Comment by generall** [comment]
It looks like we are only using `time` through `chrono` now, which claims not to use vulnerable API: https://github.com/chronotope/chrono/issues/602#issuecomment-1075915577

**Comment by generall** [comment]
removed in https://github.com/qdrant/wal/commit/a2d582776598a55d37b185377dbfafa7d57c51f4
