### ISSUE TITLE
What is the license for this crate?

### ISSUE THREAD

**Issue by akesling** [qdrant/wal#49]
Perhaps I'm overlooking it, but I don't see a license mentioned in this repo.

Out of curiosity, is there an intended license for this crate?  I see that it's used by qdrant/qdrant which is Apache licensed.  Is the intent for that to apply here as well?

**Comment by timvisee** [comment]
Thank you for bringing this to our attention!

Yes, you can apply the same license to this crate.

I've added the following PR to add it to this repository as well: https://github.com/qdrant/wal/pull/50

**Comment by akesling** [comment]
Thank you for the quick response!

@timvisee you may also want to update the [license and/or license-file field(s)](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) in Cargo.toml.  Same in the [qdrant/qdrant Cargo.toml](https://github.com/qdrant/qdrant/blob/master/Cargo.toml).  This will allow Cargo tooling to properly attribute things.
